jobs:
  include:

    - stage: docker build
      services:
        - docker
      script:
        - docker build -f Dockerfile . -t tomato:latest
        - docker tag tomato:latest bmltenabled/tomato:latest
        - docker tag tomato:latest bmltenabled/tomato:$TRAVIS_COMMIT
      before_deploy:
        - chmod +x push-docker-image.sh
      deploy:
        - provider: script
          script: "./push-docker-image.sh"
          skip_cleanup: true
          on:
            branch: travis

    - stage: deploy to ecs
      if: branch IN (travis) AND type != pull_request
      env:
        - AWS_DEFAULT_REGION=us-east-1
        - secure: "TGAVwiI/mqteZiPVqzDbDWG0+A9M0cyU7dG4pFVPhWxDomnLGlqQ/XBuVQo420dE34bVbHn4qDUpj4FgoaTwYDGSYEqxdaYjulEfD8AXUZ7d0eemNd0mt87KCoEk1Lt7a+PkwxD2fu2hPcWmW+7oedcMYCC4UX/DcVXlLsSPkMhL/FDzC55JsZwoUOFH6RVX7Acq9ZkCXCwOFNLevh3A4oAVpdhSu0mcubC+b22hRJPvUsjenoO9h5aZcVRWiHKMS5RGn+8+rs2xjAEBkZ/cTc8yO/SvE9kG5yfWIxrPffRWqhbjaXJZK+tu6f2NCfM1ohW/1dRVQjeWMG48q1lMB6e1vU01HXm03s5gkjLvNTGKbMukmUdH8B+q2LGcyTI81gK5jCCwSyJdJ7T8q0NUEa6aJDlNKoJNoMtsNRVom2ttjAIY0aZ6+Yg1fUzrJBi08HSdM4vpDl8EQeaZoHTPJK15DSeNgHmQ3Bi0NYXtNzgM9/hwxNx9XsZeHQgHQOKb/8vKaJAnhrS8TPsIe/fNXLIFN2UngVsVhJXcE0Z0dOX+L+nroJyXn25a0oEREgimm1+fgmiKjUm+ECLb4uxQl3OgoUQDSzJT1ZNxmeo+sjfy7KXcYVHx26k5fb1nhBMVC9jD7IydzMboWCywTgbGhpbCkyuXhSHlroRL6fbIbWI="
        - secure: "VkAABOgHkDhG8UVgEe3Nwcpj9ro4y7Yc3JTmp2ZqAlxasYfZttwiChU0E0xC8nvKCEb4jxzH5/X/BiBQz3JG7W3+bt/Eqrxr+rOhTGm5hUz7xsCq96TzCgw/pdjIPURLnjHeOo0sWPpBiTf7L5gXxGR2CVOZLlvdK2kaxzB057mNy4Rm5ZqZ0PQyMa/DbITF6GNK0Z/HuP96KfpxSG/Agrh/NWxqfF1bfiuvGRXWU88w0yXpNVNPdSxwHiQU8PGkJN7O0jAUKyFtQCNwMYS/Mm7MIKO0pYyR8PkMBcnlm4VfZc84wB08OpvDixHzR5MC7S9d+NAMi75WmGMOQF1kVWmkyBOkLMR6lwVlEBGA1PxBLwYQXFlwT29orM96ZIVRpSqw2npw0V/Ci9UuVC+HDtKlgAI75rHJF8YRfOll129Br1UZJ4+U7QzmWSSRPVSV8vC4D35lmqHqruttp50/2dte1bN0HbqpMUIJSkFEKHuE/WVqRU79GzZPVShLRJLgN35K+sydP+UsjTAw697TD8KPbTNDU0MOqAhAPoGfOXJEMnjalpEC8EbmTqhVbNOSxK0lI1nQ8KNVSN2p6DbOaK+92N/98LojJ5M6w/E5wpPYBsSZvCf/zvXTVSygQkTX4CsGNGaf3MKSgHiDSFU3ZnBNpVitTm8maKl/uvX0M2A="
      install:
        - cd terraform
        - wget https://releases.hashicorp.com/terraform/0.12.8/terraform_0.12.8_linux_amd64.zip
        - unzip terraform_0.12.8_linux_amd64.zip
        - rm -f terraform_0.12.8_linux_amd64.zip
      script:
        - ./terraform init -input=false
        - ./terraform plan -var image_tag=$TRAVIS_COMMIT
#        - ./terraform taint -allow-missing aws_ecs_task_definition.bmlt_$(if [ $TRAVIS_BRANCH == "master" ]; then echo latest; else echo unstable; fi)
#        - ./terraform apply -input=false -auto-approve

