jobs:
  include:

    - stage: docker build
      if: branch IN (travis)
      services:
        - docker
      script:
        - docker build -f Dockerfile . -t tomato:latest
        - docker tag tomato:$TRAVIS_COMMIT bmltenabled/tomato:$TRAVIS_COMMIT
      deploy:
        - provider: script
          script: push-docker-image.sh
          skip_cleanup: true
          on:
            branch: master

#    - stage: deploy to ecs
#      if: branch IN (master) AND type != pull_request
#      env:
#        - AWS_DEFAULT_REGION=us-east-1
#        - secure: "He2FsOfRQILckDqmVInhUeG743pp2baqSBOvpX+JQogDwNIMeLbSdC59bb+9twaAoWvGJzZjcxrkO3QQoPwCMFuSUE8wU/YIfDsYJY0ONaRYvAX/ZnpRKHVePBwJccOfUGnk+62EubM3n3QoiFa/h6NzQ6EzjR1fyg0q30jmpOA2H+tLhFjTd7RZKW3ZoboTUtYQUY/Ql9mmoTXOENqqtHaSaeA7v+ttwauHrsxixRx95Vlaza3VLfqM82O26IBs7MWNZbnv/MStKB/HUkJM/U79OXochnrRge/rWvKa6UoJ9Smcb65F3/yf4p4ykzp0i+hgmoWBIBQPH7DTb6KnFAAfgdSNeW9NJtxVxgOEHBXExf60jWbVEB2xspJlfnfLaXh8Cn0f83mJzYrbf55znDQhvo8e5myh+zifRuDGbMpfCJRbLbDDFx1hY0D8ZOTUpaoMLVJBmHhInaGj7hOnRYgG4QgvnNIgGuaLyuvWQPZgdTsXXZ/BM0Hv9ITT2xPiKMmQHArbjXV/cm+u7GKpRZpnvYcOPlqB/eFRpCJCro7tFYqfYzH4ReZDhnH+zKpqpI6MMwp6bAqYwcytRJWHfGzQTT0uxKe5ZYdQzBRWYV6dZmOKZt4YIwRwP2H+aSbHvfvm5mWVbZ8KX+bx0t+jQtElHditTfjM1zGOYCX6/mw="
#        - secure: "IursVz2FVP2sCdHJ/Ap/MYqV7/5Eg66XAEVwaw1YyelQlZZG5fzforR+vcY24sA1fuWnl5GFHBP6RheKU0G4rQL2CglF+SnolE1kOjL6eRSJdwRQlMH06qjPmEJdmjxHcl5MwIPI6suTwjSJqfkKfNccMkptW6BIdGvG9T4cEFyJVuRbbmKaMN7WiX8ouHN7VNns7TRMKBQ37KFLrKhwzKEyQ+6nBc5fWQUmQVsPQrvIxA5DYLzq/ZqTnABTC0sv8pjtI9zJYCn0LCu4mNXW8tdD4vKUW20mTAAYSUq/csMSF8PwnvXTcSDO2963/WoqjsG+f1jwcsD4TOedNNrV7Rgkq62lVae9edmlAyNiXvoqSK2adYALRVwC0oFsLEcDBihactPFkDNZxbbc4Wa+Rp3MesVCFFiCXTdQkE5blx5H2ghsmELlXjGOJ5YBA05cvZz3tb/sXlNzU0Zl3J/v4vjr2YMqmX7gyjW+exv/5yVoEieduu3ojnd7a8bWswq7CHuf0+fJ/hg0AJBfrT/wS1f+jY3Ru2tyIe3162cjehjZkoLBwC5GUBYn51Z692mbrY159ktcKoMybcuMAq1XahSLNPntG8ZeFxH2ywE8V1guk3t6zoB19W+w/4tYUoOUoYyi8TsLuuaLAghg9idj1KtcIJiOBFJTR/ZKQtc3ypQ="
#      install:
#        - cd terraform
#        - wget https://releases.hashicorp.com/terraform/0.12.8/terraform_0.12.8_linux_amd64.zip
#        - unzip terraform_0.12.8_linux_amd64.zip
#        - rm -f terraform_0.12.8_linux_amd64.zip
#      script:
#        - ./terraform init -input=false
#        - ./terraform taint -allow-missing aws_ecs_task_definition.bmlt_$(if [ $TRAVIS_BRANCH == "master" ]; then echo latest; else echo unstable; fi)
#        - ./terraform apply -input=false -auto-approve

